name: Create Deployment

on:
  push:
    branches:
      - main
"permissions": {
      "actions": "write",
      "checks": "write",
      "contents": "write",
      "deployments": "write",
      "environments": "read",
      "issues": "write",
      "metadata": "read",
      "pull_requests": "write",
      "repository_hooks": "write",
      "statuses": "write",
      "workflows": "write"
    }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{"ref":"refs/heads/main","payload":"{ \"deploy\": \"migrate\" }","description":"Deploy request from GitHub Actions"}'
