name: Create Deployment

on:
  push:
    branches:
      - main
permissions:
  contents: write  # Allows writing to the repository contents
  actions: write   # Allows using GitHub Actions
  deployments: write  # Allows creating deployments
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
               "ref": "refs/heads/main",
               "payload": "{ \"deploy\": \"migrate\" }",
               "description": "Deploy request from GitHub Actions",
               "required_contexts": []  
             }'

